# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Francesco Giovannini'
tagline:          'Computational neuroscientist'
description:      'I am a Research Assistant and PhD Student in the <a href="http://neurosys.loria.fr">Neurosys Team</a> at <a href="http://www.inria.fr/en/centre/nancy">INRIA Nancy</a> and <a href="http://www.loria.fr">LORIA</a>. My work focuses on modelling the memory system under general anaesthesia.'
url:              http://joernano.github.io
baseurl:          /

dirlist:
    downloads:  'downloads'

author:
  name:           'Francesco Giovannini'
  url:            https://joernano.github.io
  img:            'img/FrancescoGiovannini.jpeg'

icons:
    github: 'img/github.png'
    linkedin: 'img/linkedin-bw.png'
    email: 'img/email.png'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/joernano/joernano.github.io
