# Dependencies
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    auto_ids: true
    syntax_highlighter: rouge
    smart_quotes: lsquo,rsquo,ldquo,rdquo

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            'Francesco Giovannini'
tagline:          'Computational neuroscientist'
description:      'I am a Research Assistant and PhD Student in the <a href="http://neurosys.loria.fr">Neurosys Team</a> at <a href="http://www.inria.fr/en/centre/nancy">INRIA Nancy</a> and <a href="http://www.loria.fr">LORIA</a>. My work focuses on modelling the memory system under general anaesthesia using biologically-inspired spiking neural networks and physiological recordings of neural activity.'
#url:              http://joernano.github.io
#url:              http://joernano.com
url:              http://francescogiovannini.com
baseurl:          /

dirlist:
    downloads:  'downloads'

author:
  name:           'Francesco Giovannini'
  url:            https://joernano.github.io
  img:            'img/FrancescoGiovannini.jpeg'

icons:
    github: 'img/github.png'
    linkedin: 'img/linkedin-bw.png'
    email: 'img/email.png'

paginate:         5

# Custom vars
version:          2.3.0

github:
  repo:           https://github.com/joernano/joernano.github.io
